name: Lint

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened, ready_for_review]
  push:
    branches:
      - main

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Lint
        run: ./hadolint.sh ./runner/Dockerfile
