name: Publish

on:
  push:
    branches:
      - main

jobs:
  image-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.10.0
        with:
          platforms: linux/amd64
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./runner
          push: true
          platforms: ${{ steps.buildx.outputs.platforms }}
          provenance: true
          tags: |
            na2na/self-hosted-runner:develop
            na2na/self-hosted-runner:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
